### ISSUE TITLE
AES/GCM: message length exceeds maximum

### ISSUE THREAD

**Issue by EmadHassanin** [cobilab/cryfa#2]
Dear Morteze,

I am testing some encryption tools for bam files. Cryfa works perfectly on exome file, but can not work with bigger genome file.

I am using this command

```
cryfa -f -k simonsSS6004478.srt.aln.key -t 1 Data/simonsSS6004478.srt.aln.bam > Compression/output/simonsSS6004478.srt.aln.1.cryfa
```
and the issue is
```
This is not a FASTA/FASTQ file and we just encrypt it.
Encrypting...
Caught InvalidArgument...
AES/GCM: message length exceeds maximum
Done, in 620.7435 seconds.
```
and the output is much small file (64 GB) than the original bam file (106 GB).

I would like to ask for any suggestion for that, as I read on google that AES/GCM has strange behaviour when the maximum message size of ~64G is exceeded .

Thanks in advance,

Emad

**Comment by smortezah** [comment]
You can split the file, e.g. with "split" command, and encrypt each chunk. After the decryption, you can concatenate the chunks, e.g. with "cat" command.
